### ISSUE TITLE
SaaS Functionality

### ISSUE THREAD

**Issue by alexspgn** [alexspgn/saas-website#1]
Hi @melissaroy,

I'm having a weird issue where Markbot thinks my nav links don't change colours on hover, even though they do when I test it.

Do you know what the problem could be?

<img width="523" alt="screen shot 2017-04-26 at 10 31 35 pm" src="https://cloud.githubusercontent.com/assets/22139591/25465436/34a4c7d0-2ad0-11e7-8348-3c9b17a64717.png">

Thanks.

**Comment by melissaroy** [comment]
Hi @AlexSpagnuolo 
Markbot tends to looks for a:hover for the hover state. I notice you have .footer-link:hover which would need to be;
a.footer-link:hover;

Let me know if this helps

**Comment by alexspgn** [comment]
Thanks for the response! 

I tried this and played around some more and finally got it.
